### ISSUE TITLE
Missing Type: ImportDeclaration

### ISSUE THREAD

**Issue by tmcnab** [kamicane/harmonizer#1]
Guessing it's not supported as of yet, but for funzies here's the stack trace (Node v0.10.28):

``` js
node_modules/harmonizer/node_modules/nodes/lib/factory.js:475
  if (!NodeClass) throw new Error('missing type: ' + type);
                        ^
Error: missing type: ImportDeclaration
    at build (node_modules/nodes/lib/factory.js:475:25)
    at Array.map (native)
    at build (node_modules/harmonizer/node_modules/nodes/lib/factory.js:491:37)
    at transform (node_modules/harmonizer/index.js:56:17)
```

**Comment by kamicane** [comment]
done!

https://github.com/kamicane/harmonizer/commit/fc6d7cc8ecbb7eeb30dde802ff4b067dcedb8f1e
https://github.com/kamicane/nodes/commit/16f903cf47abc5710b37ef1975f7fe3b36b2ebc4

**Comment by tmcnab** [comment]
Awesome, I'll give it a shot. Thanks @kamicane!
